// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tarifuygulaması.Data;

#nullable disable

namespace tarifuygulaması.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528151153_UpdateImageAppDbContext")]
    partial class UpdateImageAppDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("tarifuygulaması.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Tatlılar"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Çorbalar"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Etli Yemekler"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Mezeler"
                        });
                });

            modelBuilder.Entity("tarifuygulaması.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Miktar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Tereyağı",
                            Miktar = "125 gr",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Bitter Çikolata",
                            Miktar = "100 gr",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Yumurta",
                            Miktar = "2 adet",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Şeker",
                            Miktar = "1 su bardağı",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Un",
                            Miktar = "2 su bardağı",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Vişne",
                            Miktar = "1 su bardağı",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Süt",
                            Miktar = "1 litre",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Pirinç",
                            Miktar = "2 su bardağı",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Şeker",
                            Miktar = "1 su bardağı",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Ad = "Nişasta",
                            Miktar = "2 yemek kaşığı",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 11,
                            Ad = "Süt",
                            Miktar = "1 litre",
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 12,
                            Ad = "Şeker",
                            Miktar = "1 su bardağı",
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 13,
                            Ad = "Nişasta",
                            Miktar = "3 yemek kaşığı",
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 14,
                            Ad = "Un",
                            Miktar = "1 yemek kaşığı",
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 15,
                            Ad = "Kadayıf",
                            Miktar = "250 gr",
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 16,
                            Ad = "Peynir",
                            Miktar = "200 gr",
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 17,
                            Ad = "Tereyağı",
                            Miktar = "100 gr",
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 18,
                            Ad = "Şeker",
                            Miktar = "1 su bardağı",
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 19,
                            Ad = "Su",
                            Miktar = "1 su bardağı",
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 20,
                            Ad = "Kırmızı Mercimek",
                            Miktar = "1.5 su bardağı",
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 21,
                            Ad = "Soğan",
                            Miktar = "1 adet",
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 22,
                            Ad = "Havuç",
                            Miktar = "1 adet",
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 23,
                            Ad = "Tereyağı",
                            Miktar = "2 yemek kaşığı",
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 24,
                            Ad = "Tuz",
                            Miktar = "1 tatlı kaşığı",
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 25,
                            Ad = "Domates",
                            Miktar = "4 adet",
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 26,
                            Ad = "Soğan",
                            Miktar = "1 adet",
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 27,
                            Ad = "Tereyağı",
                            Miktar = "2 yemek kaşığı",
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 28,
                            Ad = "Un",
                            Miktar = "1 yemek kaşığı",
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 29,
                            Ad = "Süt",
                            Miktar = "1 su bardağı",
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 30,
                            Ad = "Kırmızı Mercimek",
                            Miktar = "1 su bardağı",
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 31,
                            Ad = "Bulgur",
                            Miktar = "1 su bardağı",
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 32,
                            Ad = "Soğan",
                            Miktar = "1 adet",
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 33,
                            Ad = "Domates Salçası",
                            Miktar = "1 yemek kaşığı",
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 34,
                            Ad = "Nane",
                            Miktar = "1 tatlı kaşığı",
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 35,
                            Ad = "Yoğurt",
                            Miktar = "2 su bardağı",
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 36,
                            Ad = "Pirinç",
                            Miktar = "1 su bardağı",
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 37,
                            Ad = "Yumurta",
                            Miktar = "1 adet",
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 38,
                            Ad = "Nane",
                            Miktar = "1 tatlı kaşığı",
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 39,
                            Ad = "Tereyağı",
                            Miktar = "1 yemek kaşığı",
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 40,
                            Ad = "Patlıcan",
                            Miktar = "4 adet",
                            RecipeId = 9
                        },
                        new
                        {
                            Id = 41,
                            Ad = "Kıyma",
                            Miktar = "250 gr",
                            RecipeId = 9
                        },
                        new
                        {
                            Id = 42,
                            Ad = "Soğan",
                            Miktar = "1 adet",
                            RecipeId = 9
                        },
                        new
                        {
                            Id = 43,
                            Ad = "Domates",
                            Miktar = "2 adet",
                            RecipeId = 9
                        },
                        new
                        {
                            Id = 44,
                            Ad = "Biber",
                            Miktar = "2 adet",
                            RecipeId = 9
                        },
                        new
                        {
                            Id = 45,
                            Ad = "Dana Eti",
                            Miktar = "500 gr",
                            RecipeId = 10
                        },
                        new
                        {
                            Id = 46,
                            Ad = "Patates",
                            Miktar = "3 adet",
                            RecipeId = 10
                        },
                        new
                        {
                            Id = 47,
                            Ad = "Havuç",
                            Miktar = "2 adet",
                            RecipeId = 10
                        },
                        new
                        {
                            Id = 48,
                            Ad = "Soğan",
                            Miktar = "1 adet",
                            RecipeId = 10
                        },
                        new
                        {
                            Id = 49,
                            Ad = "Domates Salçası",
                            Miktar = "2 yemek kaşığı",
                            RecipeId = 10
                        },
                        new
                        {
                            Id = 50,
                            Ad = "Dana Eti",
                            Miktar = "300 gr",
                            RecipeId = 11
                        },
                        new
                        {
                            Id = 51,
                            Ad = "Yoğurt",
                            Miktar = "1 su bardağı",
                            RecipeId = 11
                        },
                        new
                        {
                            Id = 52,
                            Ad = "Tereyağı",
                            Miktar = "50 gr",
                            RecipeId = 11
                        },
                        new
                        {
                            Id = 53,
                            Ad = "Domates Salçası",
                            Miktar = "1 yemek kaşığı",
                            RecipeId = 11
                        },
                        new
                        {
                            Id = 54,
                            Ad = "Pide",
                            Miktar = "2 adet",
                            RecipeId = 11
                        },
                        new
                        {
                            Id = 55,
                            Ad = "Dana Eti",
                            Miktar = "400 gr",
                            RecipeId = 12
                        },
                        new
                        {
                            Id = 56,
                            Ad = "Patlıcan",
                            Miktar = "3 adet",
                            RecipeId = 12
                        },
                        new
                        {
                            Id = 57,
                            Ad = "Süt",
                            Miktar = "1 su bardağı",
                            RecipeId = 12
                        },
                        new
                        {
                            Id = 58,
                            Ad = "Tereyağı",
                            Miktar = "2 yemek kaşığı",
                            RecipeId = 12
                        },
                        new
                        {
                            Id = 59,
                            Ad = "Un",
                            Miktar = "2 yemek kaşığı",
                            RecipeId = 12
                        },
                        new
                        {
                            Id = 60,
                            Ad = "Süzme Yoğurt",
                            Miktar = "2 su bardağı",
                            RecipeId = 13
                        },
                        new
                        {
                            Id = 61,
                            Ad = "Sarımsak",
                            Miktar = "2 diş",
                            RecipeId = 13
                        },
                        new
                        {
                            Id = 62,
                            Ad = "Nane",
                            Miktar = "1 tatlı kaşığı",
                            RecipeId = 13
                        },
                        new
                        {
                            Id = 63,
                            Ad = "Zeytinyağı",
                            Miktar = "1 yemek kaşığı",
                            RecipeId = 13
                        },
                        new
                        {
                            Id = 64,
                            Ad = "Domates",
                            Miktar = "3 adet",
                            RecipeId = 14
                        },
                        new
                        {
                            Id = 65,
                            Ad = "Biber",
                            Miktar = "3 adet",
                            RecipeId = 14
                        },
                        new
                        {
                            Id = 66,
                            Ad = "Soğan",
                            Miktar = "1 adet",
                            RecipeId = 14
                        },
                        new
                        {
                            Id = 67,
                            Ad = "Maydanoz",
                            Miktar = "1 demet",
                            RecipeId = 14
                        },
                        new
                        {
                            Id = 68,
                            Ad = "Zeytinyağı",
                            Miktar = "2 yemek kaşığı",
                            RecipeId = 14
                        },
                        new
                        {
                            Id = 69,
                            Ad = "Patlıcan",
                            Miktar = "3 adet",
                            RecipeId = 15
                        },
                        new
                        {
                            Id = 70,
                            Ad = "Sarımsak",
                            Miktar = "2 diş",
                            RecipeId = 15
                        },
                        new
                        {
                            Id = 71,
                            Ad = "Zeytinyağı",
                            Miktar = "2 yemek kaşığı",
                            RecipeId = 15
                        },
                        new
                        {
                            Id = 72,
                            Ad = "Limon",
                            Miktar = "1 adet",
                            RecipeId = 15
                        },
                        new
                        {
                            Id = 73,
                            Ad = "Balık Yumurtası",
                            Miktar = "100 gr",
                            RecipeId = 16
                        },
                        new
                        {
                            Id = 74,
                            Ad = "Zeytinyağı",
                            Miktar = "1 su bardağı",
                            RecipeId = 16
                        },
                        new
                        {
                            Id = 75,
                            Ad = "Limon",
                            Miktar = "1 adet",
                            RecipeId = 16
                        },
                        new
                        {
                            Id = 76,
                            Ad = "Bayat Ekmek",
                            Miktar = "2 dilim",
                            RecipeId = 16
                        });
                });

            modelBuilder.Entity("tarifuygulaması.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GorselUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HazirlamaSuresi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KisiSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PisirmeSuresi")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Yoğun çikolata ve vişne aromasıyla nefis bir tatlı.",
                            Ad = "Vişneli Brownie",
                            CategoryId = 1,
                            GorselUrl = "/images/visnelibrowie.jpg",
                            HazirlamaSuresi = 20,
                            KisiSayisi = 6,
                            PisirmeSuresi = 35
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Fırında pişirilmiş geleneksel Türk tatlısı.",
                            Ad = "Sütlaç",
                            CategoryId = 1,
                            GorselUrl = "/images/sutlac.jpeg",
                            HazirlamaSuresi = 15,
                            KisiSayisi = 4,
                            PisirmeSuresi = 30
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Hafif yanık aromalı yumuşak sütlü tatlı.",
                            Ad = "Kazandibi",
                            CategoryId = 1,
                            GorselUrl = "/images/kazandibi.jpeg",
                            HazirlamaSuresi = 10,
                            KisiSayisi = 4,
                            PisirmeSuresi = 25
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Kadayıf ve peynirle yapılan sıcak tatlı.",
                            Ad = "Künefe",
                            CategoryId = 1,
                            GorselUrl = "/images/kunefe.webp",
                            HazirlamaSuresi = 15,
                            KisiSayisi = 2,
                            PisirmeSuresi = 20
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Klasik Türk mutfağının vazgeçilmezi.",
                            Ad = "Mercimek Çorbası",
                            CategoryId = 2,
                            GorselUrl = "/images/mercimek-corba.jpeg",
                            HazirlamaSuresi = 10,
                            KisiSayisi = 4,
                            PisirmeSuresi = 30
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Taze domateslerle yapılan hafif çorba.",
                            Ad = "Domates Çorbası",
                            CategoryId = 2,
                            GorselUrl = "/images/domates-corba.jpeg",
                            HazirlamaSuresi = 10,
                            KisiSayisi = 4,
                            PisirmeSuresi = 25
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Kırmızı mercimek ve bulgurla dolu lezzetli çorba.",
                            Ad = "Ezogelin Çorbası",
                            CategoryId = 2,
                            GorselUrl = "/images/ezogelin.jpeg",
                            HazirlamaSuresi = 10,
                            KisiSayisi = 6,
                            PisirmeSuresi = 30
                        },
                        new
                        {
                            Id = 8,
                            Aciklama = "Yoğurtlu pirinçli geleneksel çorba.",
                            Ad = "Yayla Çorbası",
                            CategoryId = 2,
                            GorselUrl = "/images/yayla.jpeg",
                            HazirlamaSuresi = 10,
                            KisiSayisi = 4,
                            PisirmeSuresi = 20
                        },
                        new
                        {
                            Id = 9,
                            Aciklama = "Patlıcan içine kıymalı dolgu ile klasik lezzet.",
                            Ad = "Karnıyarık",
                            CategoryId = 3,
                            GorselUrl = "/images/karnıyarık.jpeg",
                            HazirlamaSuresi = 20,
                            KisiSayisi = 4,
                            PisirmeSuresi = 40
                        },
                        new
                        {
                            Id = 10,
                            Aciklama = "Sebzeler ve et ile pişirilen fırın yemeği.",
                            Ad = "Etli Güveç",
                            CategoryId = 3,
                            GorselUrl = "/images/guvec.jpeg",
                            HazirlamaSuresi = 20,
                            KisiSayisi = 4,
                            PisirmeSuresi = 60
                        },
                        new
                        {
                            Id = 11,
                            Aciklama = "Yoğurt ve tereyağlı soslu dürüm kebabı.",
                            Ad = "İskender Kebap",
                            CategoryId = 3,
                            GorselUrl = "/images/iskender.jpeg",
                            HazirlamaSuresi = 15,
                            KisiSayisi = 2,
                            PisirmeSuresi = 30
                        },
                        new
                        {
                            Id = 12,
                            Aciklama = "Közlenmiş patlıcan püresi üstünde et.",
                            Ad = "Hünkar Beğendi",
                            CategoryId = 3,
                            GorselUrl = "/images/huunkar.jpeg",
                            HazirlamaSuresi = 25,
                            KisiSayisi = 4,
                            PisirmeSuresi = 45
                        },
                        new
                        {
                            Id = 13,
                            Aciklama = "Yoğurt ve sarımsaklı nefis bir meze.",
                            Ad = "Haydari",
                            CategoryId = 4,
                            GorselUrl = "/images/haydari.jpeg",
                            HazirlamaSuresi = 10,
                            KisiSayisi = 4,
                            PisirmeSuresi = 0
                        },
                        new
                        {
                            Id = 14,
                            Aciklama = "Biber ve domates ile hazırlanan baharatlı meze.",
                            Ad = "Acılı Ezme",
                            CategoryId = 4,
                            GorselUrl = "/images/ezme.jpeg",
                            HazirlamaSuresi = 15,
                            KisiSayisi = 4,
                            PisirmeSuresi = 0
                        },
                        new
                        {
                            Id = 15,
                            Aciklama = "Közlenmiş patlıcanla yapılan soğuk meze.",
                            Ad = "Patlıcan Salatası",
                            CategoryId = 4,
                            GorselUrl = "/images/patlicansalatasi.jpeg",
                            HazirlamaSuresi = 20,
                            KisiSayisi = 4,
                            PisirmeSuresi = 15
                        },
                        new
                        {
                            Id = 16,
                            Aciklama = "Balık yumurtası ile hazırlanan deniz mezesi.",
                            Ad = "Tarama",
                            CategoryId = 4,
                            GorselUrl = "/images/tarama.jpeg",
                            HazirlamaSuresi = 10,
                            KisiSayisi = 4,
                            PisirmeSuresi = 0
                        });
                });

            modelBuilder.Entity("tarifuygulaması.Models.SecurityQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Soru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SecurityQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Soru = "İlk evcil hayvanınızın adı neydi?"
                        },
                        new
                        {
                            Id = 2,
                            Soru = "Annenizin kızlık soyadı nedir?"
                        },
                        new
                        {
                            Id = 3,
                            Soru = "İlk öğretmeninizin adı neydi?"
                        },
                        new
                        {
                            Id = 4,
                            Soru = "Doğduğunuz şehir neresidir?"
                        },
                        new
                        {
                            Id = 5,
                            Soru = "Çocukken en sevdiğiniz yemek neydi?"
                        });
                });

            modelBuilder.Entity("tarifuygulaması.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BasarisizGirisSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SecurityQuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SecurityQuestionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("tarifuygulaması.Models.Ingredient", b =>
                {
                    b.HasOne("tarifuygulaması.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("tarifuygulaması.Models.Recipe", b =>
                {
                    b.HasOne("tarifuygulaması.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tarifuygulaması.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("tarifuygulaması.Models.User", b =>
                {
                    b.HasOne("tarifuygulaması.Models.SecurityQuestion", "SecurityQuestion")
                        .WithMany("Users")
                        .HasForeignKey("SecurityQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityQuestion");
                });

            modelBuilder.Entity("tarifuygulaması.Models.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("tarifuygulaması.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("tarifuygulaması.Models.SecurityQuestion", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("tarifuygulaması.Models.User", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
